### ISSUE TITLE
npm scripts doesn't work on windows ($2)

### ISSUE THREAD

**Issue by sokra** [webpack-contrib/webpack-defaults#51]
``` text
> yarn run serve:dev src

yarn run v0.21.3
$ nodemon $2 --exec babel-node src
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node $2 src`
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\...\my-loader\$2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (C:\...\my-loader\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
[nodemon] app crashed - waiting for file changes before starting...
```

The `$2` in `"serve:dev": "nodemon $2 --exec babel-node",` is linux bash syntax and doesn't work on windows. Changing it to `"serve:dev": "nodemon src --exec babel-node",` works fine.

**Comment by sapegin** [comment]
We don’t have `serve:dev` script and `$1` is not used anywhere: https://github.com/webpack-contrib/webpack-defaults/blob/master/src/tasks/package.js I think is was removed in #49.

**Comment by sokra** [comment]
ah ok... It's just not released yet.
